export const state = {
    view: 'initial', // initial | project
    sidebarOpen: false,
    history: [],
    isGenerating: false,
    activeFile: 'index.html',
    webContainerLoaded: false,
    serverUrl: null,
    files: {
        'index.html': { content: '<!-- Waiting for generation... -->' },
        'styles.css': { content: '/* Global styles */\nbody {\n  margin: 0;\n  font-family: sans-serif;\n  background-color: #ffffff;\n}' },
        'script.js': { content: '// Interactive logic\nconsole.log("Hello world");' },
        'package.json': { content: '{\n  "name": "lovable-project",\n  "type": "module",\n  "dependencies": {\n    "serve": "latest"\n  },\n  "scripts": {\n    "start": "serve ."\n  }\n}' },
        'README.md': { content: '# Project\n\nGenerated by Lovable.' }
    }
};